### ISSUE TITLE
[Property Request]: 5310/11 eligibility

### ISSUE THREAD

**Issue by safrazier17** [cal-itp/crm-helpdesk#100]
### Name of Custom Property

5310/5311 eligibility

### What is the problem that this is solving?

Caltrans has specific responsibilities and resources for 5310/5311 agencies, which represent classes or subsets of the transit agency landscape. It would be useful for me to be able to identify or filter based on this property so I could communicate with these agencies directly and assess what information we have already collected about them.

### Object Association

Companies

**Comment by AnthonyRollins** [comment]
@safrazier17 We are discussing the possiblity of having a `Grants Eligibility` as a property attached to transit agencies in #101 - might be worth hearing your thoughts on this over there.

**Comment by AnthonyRollins** [comment]
@safrazier17 5310/5311 have been uploaded as a new property with the following options;

1. 5310 Eligible
2. 5310 Applied
3. 5310 Awarded
4. 5311 Eligible
5. 5311 Applied
6. 5311 Awarded

[County of Los Angeles Hubspot Record](https://app.hubspot.com/contacts/5519226/company/8982340141)

![Screen Shot 2022-08-29 at 1 46 10 PM](https://user-images.githubusercontent.com/25047205/187295696-e2b110a3-f8bd-4192-a169-96fbc8305c4f.png)

Let me know if you need anything else with this property or if I am good to close this out.

**Comment by safrazier17** [comment]
I think this is too granular. I'm not sure there's a use case where we care _which_ of 5310/11 the agency has. Additionally I don't know that we care about all of the different stages of grant disbursement. Eligibility is the key characteristic here, for my purposes. @AnthonyRollins

**Comment by AnthonyRollins** [comment]
@safrazier17 Good to know. We had the data to fill in those other tags; `5311-Applied` and `5311-Awarded`, so I thought it couldn't hurt to include them alongside the Eligibility. Let me know if I should change these fields in any way; if not, I can close out this issue.

**Comment by safrazier17** [comment]
Yes or no would be preferred I think

**Comment by AnthonyRollins** [comment]
Ok, I can go ahead an update this field.

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC Let's talk about this on our call this week, or we can discuss changes for the property here. Let's change this property to `Grants` and then add `5311` as an option so we can all the grants to the mix. Each Grant we add to a transit agency profile will be only for the ones they have received.

**Comment by ProvvidenzaC** [comment]
This property has been updated to 5310/5311 Eligible with a Yes/No dropdown per the collective chats between us three.
