### ISSUE TITLE
[Property Request]: 3 properties to show MSA vendors selected

### ISSUE THREAD

**Issue by o-ram** [cal-itp/crm-helpdesk#112]
### Name of Custom Property

Category A Vendor (PADs); Category B Vendor (Transit Processor); EPAY

### What is the problem that this is solving?

These 3 custom properties will allow someone looking at the payments pipeline to know which vendors an agency ends up signing contracts with. Each should be a multi-select field with the following options

**Category A Vendor (PADs):**
SC Soft
Kuba
Init

**Category B Vendor (Transit Processor):**
Littlepay
Init
Bytemark
Enghouse

**EPAY:**
Elavon
Fiserv

### Object Association

Deals

### When does this property need to be implemented?

ASAP

**Comment by o-ram** [comment]
@AnthonyRollins here's what I mentioned earlier...I put "deals" as the object association but open to discussion. (and sorry if I should've created 3 separate issues for each custom property. I decided to do one because they are all similar but let me know if that wasn't the right choice)

**Comment by AnthonyRollins** [comment]
I think one issue makes sense here.

I only have one question regarding this new property, is there strong reasoning for having three separate properties? Using a multi-select, you can choose any number of options, even if they are all in one property. Let me know if that works and if not, we can create three separate properties.

**Comment by o-ram** [comment]
@AnthonyRollins the thought was 3 because these are 3 separate contracts. Category A, category B, and EPAY. And there can be any combo of vendors within them. I suppose it could be one property as long as the options label the vendors by category (particularly for Init since they are in 2 categories).

**Comment by AnthonyRollins** [comment]
@o-ram So, if we were to combine into one property, it would read:

Multi-select Property Name: `Agency signed contracts`
- Category A: SC Soft
- Category A: Kuba
- Category A: Init
- Category B: Littlepay
- Category B: Init
- Category B: Bytemark
- Category B: Enghouse
- EPAY: Elavon
- EPAY: Fiserv

Does this look right? If so, I can create this property.

**Comment by o-ram** [comment]
@AnthonyRollins looks good to me!

**Comment by AnthonyRollins** [comment]
I’ll get this added in.

**Comment by AnthonyRollins** [comment]
@o-ram This has been added to Deals. Let me know if you have some data we can test to ensure it provides what you need.

**Comment by o-ram** [comment]
It's just what I needed! I filled it out where it was needed. Thanks!
