### ISSUE TITLE
[New User Request]: Julia Schaumburg

### ISSUE THREAD

**Issue by JGSchaumburg** [cal-itp/crm-helpdesk#117]
### Email address

julia.s@jarv.us

### Full name

Julia Schaumburg

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

No

**Comment by AnthonyRollins** [comment]
@JGSchaumburg It looks like you have a login for Hubspot, so I reset your password; let me know if you got in.

**Comment by AnthonyRollins** [comment]
Hey @JGSchaumburg, I wanted to check in and see if you were able to gain access to your account in Hubspot. Let me know if you need anything.

**Comment by AnthonyRollins** [comment]
@JGSchaumburg, Were you able to get in? I was going to close out this issue; let me know!

**Comment by AnthonyRollins** [comment]
I am going to close out on this; let me know if you need anything, @JGSchaumburg
