### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/crm-helpdesk#120]
### Email address

jameelah.y@jarv.us

### Full name

Jameelah Young

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
@j-meelah You can [book a training ](https://calendar.app.google/g6qxpqW9PWyMkdKr6) with me, so we can go over the pipelines and how we have been using them. It should only take 30 mins, but if you need longer, we can do that too. You should see an invite from Hubspot today; please follow the steps to create your account.

**Comment by AnthonyRollins** [comment]
@j-meelah, I was going to close out this issue. Did you need anything else or have any questions about Hubspot?

**Comment by AnthonyRollins** [comment]
I am closing this task, let me know if you need anything @j-meelah
