### ISSUE TITLE
[Property Request]: New property GROUP w 11 new properties - GTFS Static Features

### ISSUE THREAD

**Issue by safrazier17** [cal-itp/crm-helpdesk#121]
### Name of Custom Property

GTFS Static Features

### What is the problem that this is solving?

# Overview
In development of the new Transit Data Guidelines version 3, we are employing a new organization of the many "checks" Cal-ITP uses to assess GTFS feed quality. This new organization is based around "features" of GTFS static feeds. Going forward we will assess feed quality with the following features as individual dimensions of quality:

Static Feature |  
-- | --
Compliant / On the Map | Majority of customers can see the transit service in their trip planner.
Complete | Represents all routes/services.
Fixed-Route Complete | Represents all fixed-routes/services.
Demand-Responsive Complete | Represents all demand-responsive routes/services.
ADA Accessible | Navigable by a person in a wheelchair
Accurate | Matches what is in service.
Up to Date | Available for current service and planned service operations over next 7 days.
Fares | Customers can understand what they are expected to pay and how in trip planners.
Payments Ready | Can rely on shapes, directions, and route names.
Real-time Ready | Can rely on trip IDs, has shapes, has headsigns.
Best Practices | Consistent with GTFS Best Practices and “Should” statements in specification.

# Requirements
We would like to create a new property group for the companies object called `GTFS Static Features`, and to associate the following properties with that property group:
* On the Map
* Complete
* FR Complete
* DR Complete
* ADA Accessible
* Accurate
* Up to Date
* Fares
* Payments Ready
* Real-time Ready
* Best Practices

Each of the new properties listed above should be a dropdown selector with the following options:
* Assessment Pending *[(Default value)]*
* Not Applicable
* Unwanted
* Needed
* Planned
* Ready
* In-progress
* Blocked
* Complete
* Issue Raised

### Object Association

Companies

### When does this property need to be implemented?

8/15/22

**Comment by AnthonyRollins** [comment]
@safrazier17 Generally, we are looking at adding 11 new properties, each with the same ten options under them. So, for example; 

`Property Name`: GTFS Schedule: On the Map
`Dropdown field option`: Needed

Preview of Property:
<img width="754" alt="Screen Shot 2022-08-10 at 3 40 52 PM" src="https://user-images.githubusercontent.com/25047205/184032788-ada7893c-e37f-4be2-9814-931fd5bd7801.png"> 

Does this approach work, or am I missing something important to this property?

**Comment by AnthonyRollins** [comment]
@safrazier17 Just want to make sure you see this comment

**Comment by safrazier17** [comment]
Hmm I sent a response via email looks like it didn’t make it. 

Here it is: Yes I believe so. It is my understanding that the property group would help for display purposes though. Correct me if that’s off base

**Comment by thekaveman** [comment]
I ran across this HubSpot forum post: [Examples of when to use "Property Groups"?](https://community.hubspot.com/t5/CRM/Examples-of-when-to-use-quot-Property-Groups-quot/m-p/204357) - seems relevant.

**Comment by safrazier17** [comment]
Thanks @thekaveman, I actually also came across that. It seems to me like a reasonable use of the feature

**Comment by AnthonyRollins** [comment]
@safrazier17 @thekaveman Unfortunately, `Property Groups` are more for backend admin users than users interacting and reaching out to contacts/companies in the system. While it is helpful to group properties so I can better organize custom fields, it doesn't benefit the user looking at the company profile. 

For example, I've added `On the Map` to the new Property Group `GTFS Static Features.`
<img width="1172" alt="Screen Shot 2022-08-12 at 4 05 41 PM" src="https://user-images.githubusercontent.com/25047205/184455413-286419f0-fea5-4a46-899c-d249bb3bed9c.png">

When users look at the Company Profile, everyone will see this:
<img width="1068" alt="Screen Shot 2022-08-12 at 4 07 39 PM" src="https://user-images.githubusercontent.com/25047205/184455469-34c7cf1c-1335-482b-904f-24643828bebe.png">

So, we would need 11 properties that scroll down the left column to get all this data. I would likely recommend adding all 11 properties with GTFS Static: On the Map, so there is an identifier before each field.

**Comment by AnthonyRollins** [comment]
Fields for GTFS Static are in - let me know what you think. We would have to add six more properties based on what I see in GTFS-rt #122.
<img width="1377" alt="Screen Shot 2022-08-12 at 4 19 50 PM" src="https://user-images.githubusercontent.com/25047205/184456187-e64e950b-1fd9-416c-8fa0-a0dcf47bb7ef.png">

**Comment by safrazier17** [comment]
Looks good, @AnthonyRollins. Too bad about the property groups but your explanation makes sense. A few quick changes:

* Rename the properties "GTFS Schedule:" instead of "GTFS Static:" for consistency
* Delete `GTFS Static: Payments Ready` and `GTFS Static: Real-time Ready` as we have decided not to represent these as features
* The property `GTFS Static: Not Applicable` should be `GTFS Schedule: Complete`

**Comment by AnthonyRollins** [comment]
@safrazier17 Updated based on your requests. Let me know if you need anything else.

**Comment by safrazier17** [comment]
Thank you Anthony, looks great!

**Comment by safrazier17** [comment]
Yes I believe so. It is my understanding that the property group would help
for display purposes though. Correct me if that’s off base

**Comment by AnthonyRollins** [comment]
There are two ways to do property groups; one is only seen in the backend (admin side), and the other is added to the Companies left-hand sidebar, but those fields are entirely customizable. They don't need properties to be in a group on the admin side to add them.
