### ISSUE TITLE
[Property Request]: New property GROUP w 6 new properties - GTFS-rt Features

### ISSUE THREAD

**Issue by safrazier17** [cal-itp/crm-helpdesk#122]
### Name of Custom Property

GTFS-rt Features

### What is the problem that this is solving?

# Overview
In development of the new Transit Data Guidelines version 3, we are employing a new organization of the many "checks" Cal-ITP uses to assess GTFS-realtime feed quality. This new organization is based around "features" of GTFS-rt feeds. Going forward we will assess feed quality with the following features as individual dimensions of quality:

Realtime Feature |  
-- | --
Compliant On the Map | Majority of customers can see the real-time transit service in their trip planner with updated vehicle positions, trip updates and alerts
Complete | Represents all routes/services.
Fixed-Route Complete | Represents all fixed-routes/services.
Demand-Responsive Complete | Represents all demand-responsive routes/services.
Best Practices | Consistent with GTFS Realtime Best Practices and “Should” statements in specification.
Accurate | Precision and accuracy sufficient to provide accurate trip planning information to customers.

# Requirements
We would like to create a new property group for the companies object called `GTFS-rt Features`, and to associate the following properties with that property group:
* On the Map
* Complete
* FR Complete
* DR Complete
* Best Practices
* Accurate

Each of the new properties listed above should be a dropdown selector with the following options:
* Assessment Pending *[(Default value)]*
* Not Applicable
* Unwanted
* Needed
* Planned
* Ready
* In-progress
* Blocked
* Complete
* Issue Raised

### Object Association

Companies

### When does this property need to be implemented?

8/15

**Comment by AnthonyRollins** [comment]
Property options are added but not available on the left sidebar of a company profile. Waiting on #121 to determine if this is the direction we should go.

**Comment by safrazier17** [comment]
Ok to proceed with caveats in #121

**Comment by safrazier17** [comment]
Can we add these to the About sidebar as well? (Does it make sense to use a different sidebar section for these GTFS properties? that may be what I was trying to accomplish with the property groups) @AnthonyRollins

**Comment by AnthonyRollins** [comment]
@safrazier17 Ok, it doesn't look like I need to change anything based on #121 unless I miss something. There is no need to change `Not Applicable` to `Complete,` and these features should be called "GTFS-rt." If everything looks good to you, I can close this ticket and add these properties to the left sidebar of the Company profile.

**Comment by safrazier17** [comment]
Yep, ready for you to close
