### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by segacy1** [cal-itp/crm-helpdesk#123]
### Email address

segacy@compiler.la

### Full name

Segacy Roberts

### What do you I want to do in Hubspot

- [x] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

**Comment by AnthonyRollins** [comment]
Added to Hubspot on 8/11/22
