### ISSUE TITLE
[New User Request]: Eric Dasmalchi (migrate Jarvus to Caltrans)

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/crm-helpdesk#124]
### Email address

eric.dasmalchi@dot.ca.gov

### Full name

Eric Dasmalchi

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

No

**Comment by edasmalchi** [comment]
after creating, feel free to remove the eric.d@jarv.us account. Thanks!

**Comment by AnthonyRollins** [comment]
What pipelines do you need access to?

**Comment by edasmalchi** [comment]
thanks! actually I probably don't need to be added to any pipelines for the time being, will let you know if that changes

**Comment by AnthonyRollins** [comment]
I am closing out this ticket, but please confirm you have access to Hubspot with your `@dot.ca.gov` email
