### ISSUE TITLE
[New User Request]: Aidan Feldman

### ISSUE THREAD

**Issue by afeld** [cal-itp/crm-helpdesk#128]
### Email address

aidan@compiler.la

### Full name

Aidan Feldman

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Not sure

**Comment by AnthonyRollins** [comment]
Invite sent.

**Comment by afeld** [comment]
Account created, thanks!
