### ISSUE TITLE
[Feature Request]: Pipeline (or Pipelines) for GRaaS and Cellular Connectivity

### ISSUE THREAD

**Issue by esquared415** [cal-itp/crm-helpdesk#129]
### Feature Request

@o-ram and I would like to request a Pipeline (or Pipelines) for GRaaS and Cellular Connectivity to 1) help us route tickets such as [this one](https://app.hubspot.com/contacts/5519226/ticket/1058027124), in which an agency asked for Cal-ITP support with replacing their GTFS vendor; and 2) enable Ali (GRaaS) and Lauren (Cellular Connectivity) to track agencies in an easily visible place within the CRM, so Gillian and others can see how many agencies are receiving technical support and where they stand in the pipeline. 

Some agencies might need just GRaaS support, some just Cellular Connectivity support, and some might need both types of help. So ... 2 pipelines?

### Is this request related to a problem?

Yes, right now, we can't easily see which agencies are receiving Ali's GRaaS support and/or Lauren's help with Cellular Connectivity. Gillian would like to be able to track these agencies (as would Olivia and I), and Ali and Lauren would like an easy and consistent way in which to track their customers.

### Use Case

Please see above fields.

### Additional Info

For help with Status / Stage names for each pipeline, please connect with Ali and Lauren + cross-check with Olivia and me:
- Ali Attari <Ali.Attari@Rebelgroup.com>
- Lauren Gilbert <Lauren.Gilbert@Rebelgroup.com>

Thanks!

**Comment by AnthonyRollins** [comment]
@esquared415 This issue template is for new features with Hubspot; any new pipelines should use the [Deals Pipeline Request Form](https://github.com/cal-itp/crm-helpdesk/issues/new?assignees=&labels=deals-pipeline&template=deals-pipelines-request-form.yml&title=%5BDeals+Pipeline+Request%5D%3A+). Would you be able to fill out that form with the info above as it has a few different questions?

**Comment by ProvvidenzaC** [comment]
This request has been sent through the Pipelines Request form.
