### ISSUE TITLE
[Property Request]: Latest Status

### ISSUE THREAD

**Issue by o-ram** [cal-itp/crm-helpdesk#131]
### Name of Custom Property

Latest Status

### What is the problem that this is solving?

The stages of the Payments Pipeline are intentionally high level, but we would like to have more context to those stages available at a quick glance. A custom property that allows for the deal owner to put in context (which would also appear in the Deal preview) would address this need.

### Object Association

Deals

### Who is responsible for updating and maintaining this property?

The payments/onboarding team. More specifics are being worked out within that team.

### Updating Cadence

Other

### When does this property need to be implemented?

9/2/2022

**Comment by AnthonyRollins** [comment]
@o-ram What options would be available to everyone? Is just the current status that exists already in the payment pipeline or is there a different set of options you want to provide?

**Comment by o-ram** [comment]
@AnthonyRollins this came out a payments related call on Wednesday and the idea is that the property would just be a text field because the options are too hard to predict. The example use case that led to this was us having agencies in the payments pipeline who may be scoping but are stuck/waiting on funding - it would be nice to see that comment when looking at the board view instead of having to find a note/click into the deal. Since that's just one example and there could be who knows how many more, we were thinking a text box where 1 sentence can go. And we don't want to have a bunch of stages.

Based on that, if you have other thoughts/suggestions, I'm wide open! I was planning on just creating this for the payments pipeline myself and opened the ticket for reporting purposes - I will hold off though if you'd like.

**Comment by AnthonyRollins** [comment]
@o-ram -- @ProvvidenzaC was going to handle getting this one set up for you, but if you went ahead and already added it, no worries. I don't have any issues with your approach; let's make sure we document those details in this issue so that we can track why the property is the way it is.

**Comment by AnthonyRollins** [comment]
I think everything looks good to me. We can close this issue out.
