### ISSUE TITLE
[New User Request]: Tiffany Chu

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/crm-helpdesk#132]
### Email address

tiffany@calitp.org

### Full name

Tiffany Chu

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [X] Not sure

### Do you need training on how to use Hubspot?

No

**Comment by AnthonyRollins** [comment]
Invite sent.
