### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by JGSchaumburg** [cal-itp/crm-helpdesk#134]
### Email address

julia.s@jarv.us

### Full name

Julia Schaumburg

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Not sure

**Comment by AnthonyRollins** [comment]
@JGSchaumburg You have a working account in Hubspot (created by this issue #117). Do you need me to reset your password?

**Comment by AnthonyRollins** [comment]
@JGSchaumburg Do you need me to reset your password or are you all set?

**Comment by JGSchaumburg** [comment]
Thank you, I'll give it a try!
