### ISSUE TITLE
Scribe use cases for creating GIFs

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#137]
Determine if Scribe has the functionality to create GIFs instead of screenshots.

**Comment by AnthonyRollins** [comment]
@thekaveman Follow up on your question for Scribe: Currently, there are no options to record a GIF, but the platform does record every single action you take on an application or a website. Here's an [example of a recording](https://scribehow.com/shared/Hubspot_Log_a_meeting__nt_oWji0Sgy2ixizlwqLIA) and the screenshots it produces via recording.

**Comment by thekaveman** [comment]
@AnthonyRollins thank you that is really helpful to see.

FYI @afeld @srhhnry - Anthony and the CRM team started using this tool Scribe to record stepping through an app (Hubspot) to produce a customer service guide w/screenshots. I asked if Scribe can output a GIF, no luck... but maybe still useful to grab the initial set of screenshots?

**Comment by AnthonyRollins** [comment]
With our upgraded plan we can now export to Google Docs - here's an [example](https://docs.google.com/document/d/1pASo5-SohDJqFap5VzeDcD-qhsQ2sngRZ7onkAv9Hac/edit#) and markdown.

**Comment by afeld** [comment]
Hadn't heard of Scribe — very slick!

> maybe still useful to grab the initial set of screenshots

Good call, thanks! cc https://github.com/cal-itp/benefits/issues/754

**Comment by AnthonyRollins** [comment]
@afeld Good to close out this ticket?
