### ISSUE TITLE
[Deals Pipeline Request]: Cubic Umo IQ API Keys

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/crm-helpdesk#138]
### Deals Pipeline Request

Cubic Umo IQ API Keys

### Access

evan.siroky@dot.ca.gov,olivia@compiler.la,scott@compiler.la

### What problem are you trying to solve for?

We are trying to get an API key for the Umo IQ application at all 20 agencies that are served by the Umo IQ application. A representative at Cubic says we have to ask someone at each agency to email Cubic and ask for an API key. Once we have an API key we should be able to download and ingest GTFS-RT data for that transit agency.

### What is the goal of the pipeline are you trying to solve for?

To receive API keys for all Umo IQ services. Once we have an API key we should be able to download and ingest GTFS-RT data for that transit agency.

### Have you used an exisiting pipeline in Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
As of 9/16, Evan mentioned on [Slack](https://cal-itp.slack.com/archives/C01CT346NDC/p1663346774006979?thread_ts=1663261638.589149&cid=C01CT346NDC) putting this on hold for now.

**Comment by AnthonyRollins** [comment]
@evansiroky Created the new [Cubic Umo IQ API Keys pipeline](https://app.hubspot.com/contacts/5519226/objects/0-3/views/9899343/board). I added in a few stages to get you started `Need Outreach`, `In Progress`, and `Received API Key`, but please let me know if you want these changed or added to.

**Comment by AnthonyRollins** [comment]
Added:  a column between `In Progress` and `Received API Key` called `Received data sharing approval`?

**Comment by AnthonyRollins** [comment]
@evansiroky Take a look at the pipeline and let me know if you have any questions; if everything looks good, I will close out this issue.
