### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by lizlindesign** [cal-itp/crm-helpdesk#140]
### Email address

liz.l@jarv.us

### Full name

Liz Lin

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [X] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
Account invite sent.
