### ISSUE TITLE
Problem with Update CRM Record issue template

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#145]
Missing markdown value in the[ issue template](https://github.com/cal-itp/crm-helpdesk/blob/main/.github/ISSUE_TEMPLATE/crm-record-update.yml).
![Screen Shot 2022-09-26 at 9 15 23 AM](https://user-images.githubusercontent.com/25047205/192328034-bbbd9780-4d5c-458e-90f4-ed68d27a41ac.png)

**Comment by AnthonyRollins** [comment]
@thekaveman When you have a moment, could you look over my .yml file and see why it isn't working?

**Comment by thekaveman** [comment]
Ah, I think it doesn't like that there are no _actual_ fields here - just the markdown text. 

One sort of silly idea is to add a radio button/dropdown field like "I will submit this issue in HubSpot" with "Yes/No" - this should pass the check above, and reinforces the HubSpot submission one extra time!
