### ISSUE TITLE
New User - Katrina Kaiser (Caltrans)

### ISSUE THREAD

**Issue by KatrinaMKaiser** [cal-itp/crm-helpdesk#154]
### Email address

katrina.kaiser@dot.ca.gov

### Full name

Katrina Kaiser

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
Invite link sent. For training on Hubspot, feel free to [pick a time](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2Vy-F1WktqBmp4kkKACHmcbPOtK0xQVNu8G9yRh-UatMa5O45npijicpl2h9UkZdcJwHiv61k5) on my calendar. You can also send your calendar to me, and I can find a time for us. Let me know if you have any questions.

**Comment by AnthonyRollins** [comment]
@KatrinaMKaiser Checking in if you want to do a Hubspot training, feel free to [pick a time](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2Vy-F1WktqBmp4kkKACHmcbPOtK0xQVNu8G9yRh-UatMa5O45npijicpl2h9UkZdcJwHiv61k5) on my calendar.
