### ISSUE TITLE
Field for "Attending x Conference"

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/crm-helpdesk#155]
### Name of Custom Property

Attending x Conference

### What is the problem that this is solving?

As a Cal-ITP staff member attending an in-person conference,
I want to know as many of the attending organizations as possible and their associated position in various pipelines/deals,
So that I can prioritize our team having in-person conversations with certain agencies that we haven't yet established contact with

I sort of envision being able to filter companies based on this new object and then extract from that a list of agencies that "are in x pipeline" or "have not been contacted" or other analyses.

### Object Association

Companies

### Who is responsible for updating and maintaining this property?

Evan Siroky

### Updating Cadence

Other

### When does this property need to be implemented?

10/30/2022

### Not sure what you need?

Unsure

**Comment by evansiroky** [comment]
I sent you some data via Slack DM.

**Comment by AnthonyRollins** [comment]
@evansiroky Thanks! Curious about this data and have a few follow-up questions. Based on your initial request, you wanted this data to be associated with "company" data meaning each organization in Hubspot, but did you want individual contacts too?

**Comment by evansiroky** [comment]
I definitely want it for the Company, but having it for Contacts too would be nice.

**Comment by evansiroky** [comment]
Also, this is preparation for the [2022 CALACT Fall Conference & Expo](https://calact.org/autumn-conference-and-expo-2022/) which is happening next week.

**Comment by AnthonyRollins** [comment]
@evansiroky Uploaded the company data with the spreadsheet you provided. You should see all the companies with a new property `attending x conference` (see screenshot) and the label `CALACT Fall 2022` 

<img width="411" alt="Screen Shot 2022-10-27 at 12 59 32 PM" src="https://user-images.githubusercontent.com/25047205/198387066-355f177a-00a3-4162-b74d-c431537d62a9.png">

Additionally, I created a [list](https://app.hubspot.com/contacts/5519226/objectLists/88) that will show you all companies attending the conference that are also in one of our beginning stages in all of our pipelines.

**Comment by AnthonyRollins** [comment]
@evansiroky I am going to close out this issue, let me know if you need anything else.
