### ISSUE TITLE
[Property Request]: 

### ISSUE THREAD

**Issue by mlgilbert18** [cal-itp/crm-helpdesk#156]
### Name of Custom Property

Cellular Data Provider

### What is the problem that this is solving?

This is going to help track which telecom an agency is using to get its data. We'll be using this to track FirstNet contract sign ons as well as general trends on provider use.

There are four main providers: AT&T, FirstNet, T-Mobile, and Verizon. We'd want this to be a dropdown menu for people to select from. 

### Object Association

Companies

### Who is responsible for updating and maintaining this property?

Lauren Gilbert will be updating this as she finds the information. Olivia R may also assist if she gets the data during intro interviews.

**Comment by AnthonyRollins** [comment]
We can get this created for you, @mlgilbert18.

**Comment by AnthonyRollins** [comment]
@mlgilbert18 This property has been created and is now showing on the left sidebar of the company profile. Let us know if you have any other questions.
