### ISSUE TITLE
Determine articles for Knowledge Base

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#165]
High-level to-dos: #164 

## To-Dos

- [ ] 

## Proposed Articles

- [ ]

**Comment by AnthonyRollins** [comment]
@o-ram, Should we remove these or rethink these for tracking? Maybe new pages we want to think through adding to MobiMart?

**Comment by o-ram** [comment]
@AnthonyRollins I think we close this one b/c, I think as the work to redesign calitp.org and continue to add to MobiMart ramps up, content issues would probably belong in that repo. And if something specific involves Hubspot/other CS functions, we can open a new ticket then. LMK if you think differently or not. If not, I can close this.

**Comment by AnthonyRollins** [comment]
We should close this and move future issues to the new repo. I want to make sure we have a plan in case we want to think through docs/resources that should be added to the website.
