### ISSUE TITLE
[Property Request]: Payment Processor

### ISSUE THREAD

**Issue by zacharykarson** [cal-itp/crm-helpdesk#185]
### Name of Custom Property

Existing Bank/Payment Processor

### What is the problem that this is solving?

It is important for the onboarding team to know and be able to easily reference information about each transit agency's existing bank and/or payment processor ("existing" meaning prior to signing any new contracts with banks/payment processors for the purpose of accepting open loop contactless payments). Currently, there is no standard location for this information. Ideally, this would also be searchable, so that, for example, a member of the onboarding team could search for all agencies in the pipeline that did not have an existing bank/payment processor.

### Object Association

Companies

### Who is responsible for updating and maintaining this property?

Deal owner

### Updating Cadence

Monthly

### When does this property need to be implemented?

2/1/2023

### Not sure what you need?

None

**Comment by AnthonyRollins** [comment]
@zacharykarson, Can you give us an example of the data you hope to have in this new property?

**Comment by zacharykarson** [comment]
![image](https://user-images.githubusercontent.com/123603668/216701445-1190732c-d37a-4306-8302-46ffc7e94017.png)

**Comment by zacharykarson** [comment]
Yeah, unfortunately I don't know of any document that has this data. It would have to be something that we would manually enter as the rest of the deal page gets filled out. That's the purpose of adding it, so that people remember to ask about this and document it early on in the process

**Comment by zacharykarson** [comment]
It will likely be one of these top companies (https://nilsonreport.com/mention/1372/1link/) or "no provider" - we may want to leave room for the person to enter current provider, but that the agency plans to switch providers too -- so more of a short answer response than a dropdown - is that possible?

**Comment by ProvvidenzaC** [comment]
Thanks for the article! So it looks like the options should be Chase, FIS, Fiserv, Wells Fargo, Global Payments, Bank of America, Elavon, PNC, Paysafe, Priority Technology Holdings and No Provider? For the note about plans to switch providers, I'm going to tag @AnthonyRollins if he has any perspective on how that could be captured within this property or be articulated through another means.

**Comment by zacharykarson** [comment]
Sounds good, I would also add a category for "Other" just in case there are
ones not on that list,
