### ISSUE TITLE
[Feature Request]:  Onboarding list for Benefits App 

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#194]
### Feature Request

MSA Onbaording team is looking for a place in the CRM where they can add a growing list of agencies wanting to "on the list" for Benefits application. This request might need a different issue form; [new property request](https://github.com/cal-itp/crm-helpdesk/issues/new?assignees=&labels=property&template=property-request-form.yml&title=%5BProperty+Request%5D%3A+) and [deals pipeline request](https://github.com/cal-itp/crm-helpdesk/issues/new?assignees=&labels=deals-pipeline&template=deals-pipelines-request-form.yml&title=%5BDeals+Pipeline+Request%5D%3A+).

### Is this request related to a problem?

 Currently there is no place to indicate that an agency is interested in using the Benefits application.

### Use Case

Having a list where Cal-ITP users can add new agencies to interested in the benefits application.

### Additional Info

n/a

**Comment by o-ram** [comment]
@AnthonyRollins after discussing this in the payments onboarding team call, we all decided that we think a pipeline is the way to go so we can track who is interested (often comes out of payments intro calls), who has launched with Benefits, etc. There may also be a desire to have a dashboard similar to the payments one that gets shared with Gillian (TBD on that though). I will open a ticket for a deals pipeline request and I think you can close this.

**Comment by AnthonyRollins** [comment]
Related to #195

**Comment by AnthonyRollins** [comment]
Closed due to the closing #195
