### ISSUE TITLE
[Deals Pipeline Request]: Benefits

### ISSUE THREAD

**Issue by o-ram** [cal-itp/crm-helpdesk#195]
### Deals Pipeline Request

Cal-ITP Benefits

### Access

Olivia, Laney, Erika, Lilly, Jennie, Kegan, Angelly, Ali, Gillian, Evan and Hunter

### What problem are you trying to solve for?

Currently there is no place to indicate and track agencies that are interested in using the Benefits application, as well as agencies that have the Benefits application currently and to what extent (i.e. MST has it for both Seniors and their unique discount card system. Upcoming agencies will only have it for seniors). This information is ideally in the CRM and is important for the holistic view of an agency's status with Cal-ITP.

### What is the goal of the pipeline are you trying to solve for?

A formal place to track agencies who have Benefits from the start of the journey (interested) to the end (launched) and with that discount types are included. Github tracks all of the development work but it does not track early interest or very high-level progress that is important to stakeholders. A pipeline would allow us to track this and potentially create a dashboard similar to the payments pipeline one.

Stages in mind at this time (these will likely need to be refined but are a good starting place and hopefully give a sense of what we are envisioning):

- Interested
- Agency onboarding
- Development
- Testing
- Launched

### Have you used an exisiting pipeline in Hubspot?

Yes

**Comment by o-ram** [comment]
@AnthonyRollins access list may grow...I also didn't include emails b/c I thought we weren't putting info like that in Github. Hopefully, names are enough!

**Comment by AnthonyRollins** [comment]
@o-ram created the [pipeline](https://app.hubspot.com/contacts/5519226/objects/0-3/views/all/board) with your first draft of stages, let me know if you have any changes.

**Comment by laneymangan** [comment]
All deals have been added into the benefits pipeline
