### ISSUE TITLE
[Property Request]: Felix label

### ISSUE THREAD

**Issue by o-ram** [cal-itp/crm-helpdesk#196]
### Name of Custom Property

Felix demonstration

### What is the problem that this is solving?

Some agencies pursuing contactless payments are also demonstrating a product called Felix on their dial-a-ride/demand response vehicles. Felix follows the same concept of a rider being able to tap with their bank card to pay their fare, but has more flexible hardware that is adaptable for demand response transit. We are currently not tracking who is involved with a Felix demo within the CRM and we would like to do so within the Payments Pipeline, as Felix is part of pursuing contactless payments.

@AnthonyRollins happy to chat about this in one of our existing calls next week; I also still need to get some more input on this from others on the payments team.

### Object Association

Deals

### Who is responsible for updating and maintaining this property?

Account managers/payments team members working with the agency on Felix

### Updating Cadence

Other

### When does this property need to be implemented?

Ideally by end of month but no firm timeline

### Not sure what you need?

Yes

**Comment by AnthonyRollins** [comment]
@o-ram Curious if there are multiple contactless payments products or if Felix is the only one. Would this property be a dropdown or multi-select, or something else?

**Comment by o-ram** [comment]
@AnthonyRollins I believe Felix is the only thing we would need to track at this moment. Unsure as to which property type would be best. Let me gather more information at the next payments onboarding team call and then get back to you.

**Comment by AnthonyRollins** [comment]
@o-ram Sounds good. I will put this on hold and wait to hear back for more details before creating the property

**Comment by o-ram** [comment]
@AnthonyRollins I ended up creating this fresh off of discussing this with Ali. The custom property is tied to "deals" and is a dropdown field. The property is called "Felix Demo" and the options are yes or no. Felix is the only product of this type we need to track within the payments pipeline, and this property fulfills the need of having visibility into who is taking part in a demo or not.
