### ISSUE TITLE
Feedback Form for Amtrak Conductors

### ISSUE THREAD

**Issue by esquared415** [cal-itp/crm-helpdesk#197]
### Feature Request

@AnthonyRollins @o-ram Thank you for working with me on creating a HubSpot-based form to collect the following information from Amtrak Conductors during the Capitol Corridor pilot. 

These are the fields that Alan of Xentrans and I would like to include in the feedback form. Unless noted as "_(optional)_," all fields are "required":

- Name _(First, Last)_
- Work email 
- Crew Base _(OAK or SAC)_
- Train #
- Vehicle # _(optional)_
- Samsung Device ID (on back of device / case)
- Date that feedback relates to
- Time that feedback relates to
- Comments _(open field)_
- Would you like to hear back from us:
     - Yes, please email me
     -  No, I just wanted to let you know
     
Please let me know if you have any Qs, and thank you!

### Is this request related to a problem?

Nope!

### Use Case

To help us gather and track input from Amtrak conductors during Capitol Corridor pilot.

### Additional Info

Please let me know if you'd like to meet again. Thanks!

**Comment by o-ram** [comment]
@esquared415 Here is a preview link to a test survey: https://survey.hsforms.com/1l_8gj3XoRZCIIHbVnrDCuQ3aanu?preview=true. You'll notice we currently have placeholders at the top for the Survey title and description - please let us know what text you would like placed there and we will insert it for you!

Other than that, let us know if you have any thoughts about the questions or things you would like changed.

**Comment by AnthonyRollins** [comment]
Updated form with Capitol Corridor logo and Cal-ITP logo. Still waiting on `form title` and `form description`.

**Comment by esquared415** [comment]
**form title**: 
Tap2Ride Feedback Form

**form description**: 
Please take a moment to share your feedback—we value all types of input and thank you in advance! –CCJPA and Caltrans' California Integrated Travel Project (Cal-ITP)

Thanks @AnthonyRollins & @o-ram! 🙌

**Comment by AnthonyRollins** [comment]
@esquared415 See updated [form](https://survey.hsforms.com/1l_8gj3XoRZCIIHbVnrDCuQ3aanu?preview=true). Let me know if you have any other edits.

**Comment by esquared415** [comment]
👋  @AnthonyRollins & @o-ram 

One add and one edit, please. And then I'll review the Feedback Form preview for publication:

- [ ] In Header, please change text to:
Please take a moment to share your feedback—we value all types of input. 
Thank you in advance, CCJPA and Caltrans' California Integrated Travel Project (Cal-ITP)
_[Note: Prefer line break between sentences. No period at end, please.]_

- [ ] In Form itself, please add below **boldface** text between the below _existing_ text fields:
_Time that feedback relates to_
**Last 4 digits of customer's bank card (if relevant)**
_Comments (open field)_

Thank you!

**Comment by AnthonyRollins** [comment]
@esquared415 [Form](https://survey.hsforms.com/1l_8gj3XoRZCIIHbVnrDCuQ3aanu?preview=true) has been updated.

**Comment by esquared415** [comment]
@AnthonyRollins and @o-ram Looks great! Please publish and send me the live link.

And then please remind me how / where in HubSpot I can see the feedback when a conductor completes the form.

Thanks again!

**Comment by AnthonyRollins** [comment]
@esquared415 Survey has been published. You can use this [link](https://survey.hsforms.com/1l_8gj3XoRZCIIHbVnrDCuQ3aanu) to send to conductors. You will get notified via your @dot.ca.gov email, and then you can navigate to the [Support Pipeline](https://app.hubspot.com/contacts/5519226/objects/0-5/views/all/board) to see the tickets. They will be in the "routed to CCJPA" or "New" section.
