### ISSUE TITLE
[Property Request]: Remove "READY" from ALL "GTFS Features" properties

### ISSUE THREAD

**Issue by safrazier17** [cal-itp/crm-helpdesk#201]
### What is the problem that this is solving?

The GTFS Features properties represent individual characteristics of high quality GTFS feeds and the status of an agency in progressing toward completing that feature.

READY is a status option on all of these properties. However, it has been decided by the implementing team that READY is duplicative of the PLANNED status. As such, we would like READY to be removed as an option.

### Object Association

None

### Updating Cadence

None

### Not sure what you need?

None

**Comment by AnthonyRollins** [comment]
@safrazier17 All properties have been updated. Let me know if you have any problems
