### ISSUE TITLE
[Property Request]: Grants

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/crm-helpdesk#208]
### Name of Custom Property

Grants

### What is the problem that this is solving?

There are several grants that transit agencies may be eligible for, we want an easy way to showcase all of the grants that a company is eligible for. We'd like to remove the existing property "5310/11 eligible" and add a custom drop-down list property that includes: 5310, 5311, 5311(f), 5307. We should be able to select multiple grants. 

### Object Association

Companies

### Who is responsible for updating and maintaining this property?

All

### Updating Cadence

None

### When does this property need to be implemented?

March 2023

### Not sure what you need?

None

**Comment by AnthonyRollins** [comment]
> @AnthonyRollins, who should I assign this property request to?

Responded via a call

**Comment by laneymangan** [comment]
Confirmed via call that this property should be named "Grant Eligibility" to clarify that this property identifies which grants a transit agency is _eligible_ for, not that they necessarily receive the grant

**Comment by laneymangan** [comment]
This property has been added to Hubspot as "Grants Eligibility" with a multi-select dropdown menu that includes 5310, 5311, 5311f, 5307.
