### ISSUE TITLE
Web forms country code not accesible 

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#212]
## To-Do
- [x] Reach out to Hubspot support
- [ ] Send update to website team

**Comment by thekaveman** [comment]
@machikoyasuda FYI, I showed Anthony and CRM team that issue you found with the MobiMart form phone number field -- going to try and run it up to HubSpot and see if they can do anything about it!

**Comment by AnthonyRollins** [comment]
Ticket submitted on April 7: https://app.hubspot.com/support-inbox/5519226/ticket/12263287

**Comment by AnthonyRollins** [comment]
I've been in touch with Hubspot's customer success team and wanted to share some discoveries:

1.  Removing the country code from the phone number field on our form no longer causes the accessibility issue. You see that in this test [form](https://share.hsforms.com/13blzRJhkSyuM3j9LUEYmGQ3aanu).
2. There is currently no timeline to fix this issue, and they recommend adding this to their product form so others upvote it.
3. Hubspot mentioned there might be some workarounds by moving the fields around, but it didn't seem like a solution that would work for us. 

If you have a Hubspot account, you can see our [support chat](https://app.hubspot.com/support-inbox/5519226/?source=widget) for the full conversation. There is no fix to the current issue for the next steps, so we would have to either remove the country code or keep the form as it is and wait for their team to fix it.

**Comment by AnthonyRollins** [comment]
I'd like to update my response from 4 days ago. I just heard from Hubspot's support with good news!

> Good morning! Great news! I dug into this further with our engineers, and they were able to locate the issue on their side and deploy a fix!

It looks like they have fixed the bug on their side. I tried it on our live site, and it works for me, but @thekaveman @machikoyasuda, let me know if you see it.

**Comment by machikoyasuda** [comment]
@thekaveman @machikoyasuda confirmed fix on Firefox and Chrome on Mac OS. This is a huge win 💯 💯 💯 💯 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by machikoyasuda** [comment]
Closing this issue now, as the web form country code is now confirmed keyboard-accessible.
