### ISSUE TITLE
Q1 Audit: Admin

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/crm-helpdesk#213]
Admin: Users, permissions

Admin section of Audit Worksheet: https://docs.google.com/spreadsheets/d/1RvvKmHigOplWY6sOumPkpK0xzg7Ez8U8Z2x2FoNR_OU/edit#gid=310378033

**Comment by AnthonyRollins** [comment]
@laneymangan We are looking for this to be completed by next week April 14th, correct?

**Comment by laneymangan** [comment]
@AnthonyRollins correct! Our audit retro is scheduled for April 20th though so there's some wiggle room if this takes longer than expected.
