### ISSUE TITLE
[New User Request]: India Kea

### ISSUE THREAD

**Issue by indiakea** [cal-itp/crm-helpdesk#229]
### Email address

india.k@jarv.us

### Full name

India Kea 

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Not sure

**Comment by AnthonyRollins** [comment]
@indiakea Invite link sent
