### ISSUE TITLE
Q1 Doc Audit: Marketing

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/crm-helpdesk#230]
Update [CRM Guide](https://docs.google.com/document/d/11SIWzGqDDJN4OADASiXywvcu9C8deXZRvTE-cdn-Lh4/edit#heading=h.av41529bmi7j)
- Hubspot forms
- Transactional emails
- New emails
- Lists

**Comment by AnthonyRollins** [comment]
The section has been updated.
