### ISSUE TITLE
Q1 Doc Audit: Admin Details (1/2)

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/crm-helpdesk#231]
Update [CRM Guide](https://docs.google.com/document/d/11SIWzGqDDJN4OADASiXywvcu9C8deXZRvTE-cdn-Lh4/edit#heading=h.itxgkrrpx0v)

- [ ] Zapier Section
- [ ] CRM Properties Section

**Comment by AnthonyRollins** [comment]
The section has been updated.
