### ISSUE TITLE
[New User Request]:Andy Walker

### ISSUE THREAD

**Issue by indexing** [cal-itp/crm-helpdesk#249]
### Email address

andy@compiler.la

### Full name

Andy Walker

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [X] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
@indexing I've added you to Hubspot with access to the deals pipelines. To schedule time with me for your Hubspot training, you can [book some time](https://calendar.app.google/YVqbDTFt592zg7xJ7) that works on my calendar. Feel free to let me know if you have any questions.
