### ISSUE TITLE
[New User Request]: Access Pipelines Please 

### ISSUE THREAD

**Issue by laurenbrennanrebel** [cal-itp/crm-helpdesk#253]
### Email address

lauren.brennan@rebelgroup.com

### Full name

Lauren Brennan

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

None

**Comment by AnthonyRollins** [comment]
@laurenbrennanrebel, What pipelines do you need access to?

**Comment by AnthonyRollins** [comment]
Updated your user settings.
