### ISSUE TITLE
Move tasks into Internal Support pipeline

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#255]
Request from Evan in [Slack](https://cal-itp.slack.com/archives/C03S1FDGZ2A/p1684787550300579) to move Hubspot tasks to the new process for adding GTFS Data Quality tasks to Internal Support Pipeline, related to a reporting issue from #238 and #248

An export of all of Evan's GTFS tasks can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1ewjVhE5PEo6O8iEYSX91ulKnjq4jeVU4EtBykBHWLzw/edit#gid=0), which still needs to be imported into the Internal Support Pipeline.

**Comment by AnthonyRollins** [comment]
@laneymangan @o-ram FYI - I'm importing Evan's tasks into the Internal support pipeline, so you might get a few notifications from this, let me know if something is right.

**Comment by evansiroky** [comment]
Thanks!
