### ISSUE TITLE
Syntax error in Issue Template Form

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#92]
YAML syntax error in [reporting_request_form.yml](https://github.com/cal-itp/crm-helpdesk/blob/main/.github/ISSUE_TEMPLATE/reporting_request_form.yml). 

![Screen Shot 2022-07-12 at 2 19 23 PM](https://user-images.githubusercontent.com/25047205/178597355-d4943ea8-0622-4469-8bbe-76cdf3b73329.png)

- [ ] Fix YAML syntax error.

**Comment by AnthonyRollins** [comment]
@angela-tran When you have a moment over the next few days, would you mind taking a look at this?

**Comment by angela-tran** [comment]
@AnthonyRollins Sure. YAML is picky about whitespace, and I think your last `- type` is not at the same indent-level as the others

**Comment by angela-tran** [comment]
That is a great question, and I have no idea. It confused me too. I ended up just visually comparing this file vs. one of your other ones .yml files. 😄
